logging:
  config: classpath:log4j2.xml
consumer:
  work-time: 100

jms:
  activemq:
    brokerUrl: "ssl://127.0.0.1:62617"
    user: user
    password: user
    concurrentConsumers: 10
    redeliveryCount: 5
    redeliveryDelayMs: 20000
    queues:
      input-output-endpoint:  "inputToOutputQueue"
      output-endpoint:        "outputQueue"