//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.11 at 02:20:11 PM MSK 
//


package ru.syntez.integration.artemis.entities;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "system",
    "data"
})
@XmlRootElement(name = "CIT_REQUEST_OUT")
public class CITREQUESTOUT {

    @XmlElement(name = "SYSTEM", required = true)
    protected CITREQUESTOUT.SYSTEM system;
    @XmlElement(name = "DATA", required = true)
    protected CITREQUESTOUT.DATA data;

    /**
     * Gets the value of the system property.
     *
     * @return
     *     possible object is
     *     {@link CITREQUESTOUT.SYSTEM }
     *
     */
    public CITREQUESTOUT.SYSTEM getSYSTEM() {
        return system;
    }

    /**
     * Sets the value of the system property.
     *
     * @param value
     *     allowed object is
     *     {@link CITREQUESTOUT.SYSTEM }
     *
     */
    public void setSYSTEM(CITREQUESTOUT.SYSTEM value) {
        this.system = value;
    }

    /**
     * Gets the value of the data property.
     *
     * @return
     *     possible object is
     *     {@link CITREQUESTOUT.DATA }
     *
     */
    public CITREQUESTOUT.DATA getDATA() {
        return data;
    }

    /**
     * Sets the value of the data property.
     *
     * @param value
     *     allowed object is
     *     {@link CITREQUESTOUT.DATA }
     *
     */
    public void setDATA(CITREQUESTOUT.DATA value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DogNum"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="22"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DogNewStatus"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="16"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DogNewDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Channel"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="100"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Depart"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="20"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dogNum",
        "dogNewStatus",
        "dogNewDate",
        "channel",
        "depart"
    })
    public static class DATA {

        @XmlElement(name = "DogNum", required = true)
        protected String dogNum;
        @XmlElement(name = "DogNewStatus", required = true)
        protected String dogNewStatus;
        @XmlElement(name = "DogNewDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dogNewDate;
        @XmlElement(name = "Channel", required = true)
        protected String channel;
        @XmlElement(name = "Depart", required = true)
        protected String depart;

        /**
         * Gets the value of the dogNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDogNum() {
            return dogNum;
        }

        /**
         * Sets the value of the dogNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDogNum(String value) {
            this.dogNum = value;
        }

        /**
         * Gets the value of the dogNewStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDogNewStatus() {
            return dogNewStatus;
        }

        /**
         * Sets the value of the dogNewStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDogNewStatus(String value) {
            this.dogNewStatus = value;
        }

        /**
         * Gets the value of the dogNewDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDogNewDate() {
            return dogNewDate;
        }

        /**
         * Sets the value of the dogNewDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDogNewDate(XMLGregorianCalendar value) {
            this.dogNewDate = value;
        }

        /**
         * Gets the value of the channel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannel() {
            return channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannel(String value) {
            this.channel = value;
        }

        /**
         * Gets the value of the depart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepart() {
            return depart;
        }

        /**
         * Sets the value of the depart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepart(String value) {
            this.depart = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="BP_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CIT_Version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ERROR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="FORMAT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MSG_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SYNC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SYS_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TAR_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bpid",
        "citVersion",
        "error",
        "format",
        "msgid",
        "sync",
        "sysid",
        "tarid",
        "version"
    })
    public static class SYSTEM {

        @XmlElement(name = "BP_ID", required = true)
        protected String bpid;
        @XmlElement(name = "CIT_Version", required = true)
        protected String citVersion;
        @XmlElement(name = "ERROR")
        protected String error;
        @XmlElement(name = "FORMAT", required = true)
        protected String format;
        @XmlElement(name = "MSG_ID", required = true)
        protected String msgid;
        @XmlElement(name = "SYNC", required = true)
        protected String sync;
        @XmlElement(name = "SYS_ID", required = true)
        protected String sysid;
        @XmlElement(name = "TAR_ID", required = true)
        protected String tarid;
        @XmlElement(name = "Version", required = true)
        protected String version;

        /**
         * Gets the value of the bpid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBPID() {
            return bpid;
        }

        /**
         * Sets the value of the bpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBPID(String value) {
            this.bpid = value;
        }

        /**
         * Gets the value of the citVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCITVersion() {
            return citVersion;
        }

        /**
         * Sets the value of the citVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCITVersion(String value) {
            this.citVersion = value;
        }

        /**
         * Gets the value of the error property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getERROR() {
            return error;
        }

        /**
         * Sets the value of the error property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setERROR(String value) {
            this.error = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFORMAT() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFORMAT(String value) {
            this.format = value;
        }

        /**
         * Gets the value of the msgid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGID() {
            return msgid;
        }

        /**
         * Sets the value of the msgid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGID(String value) {
            this.msgid = value;
        }

        /**
         * Gets the value of the sync property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSYNC() {
            return sync;
        }

        /**
         * Sets the value of the sync property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSYNC(String value) {
            this.sync = value;
        }

        /**
         * Gets the value of the sysid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSYSID() {
            return sysid;
        }

        /**
         * Sets the value of the sysid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSYSID(String value) {
            this.sysid = value;
        }

        /**
         * Gets the value of the tarid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTARID() {
            return tarid;
        }

        /**
         * Sets the value of the tarid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTARID(String value) {
            this.tarid = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }

}
